# Generated by Django 6.0.1 on 2026-01-29 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Fecha cuando se registró la desconexión",
                    ),
                ),
                (
                    "platform_client",
                    models.CharField(
                        blank=True,
                        help_text="Cliente/plataforma que reportó el evento",
                        max_length=100,
                    ),
                ),
                (
                    "last_connection",
                    models.DateTimeField(
                        help_text="Última conexión registrada del vehículo"
                    ),
                ),
                (
                    "problem",
                    models.CharField(
                        blank=True, help_text="Descripción del problema", max_length=255
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, help_text="Tipo de desconexión", max_length=50
                    ),
                ),
                (
                    "last_status",
                    models.CharField(
                        blank=True, help_text="Último estado conocido", max_length=50
                    ),
                ),
                (
                    "comentario",
                    models.TextField(blank=True, help_text="Comentarios adicionales"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "distribuidor",
                    models.ForeignKey(
                        help_text="Distribuidor asociado en el momento del evento",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registers",
                        to="organization.distribuidor",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        help_text="Vehículo asociado al registro",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registers",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Desconexión",
                "verbose_name_plural": "Registros de Desconexión",
                "ordering": ["-report_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Bitacora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comentario",
                    models.TextField(
                        blank=True, help_text="Comentario sobre la acción"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la acción",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bitacora_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "register",
                    models.ForeignKey(
                        help_text="Registro asociado",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bitacora_entries",
                        to="registers.register",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bitácora",
                "verbose_name_plural": "Bitácoras",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="register",
            index=models.Index(
                fields=["vehicle", "report_date"], name="registers_r_vehicle_728da5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="register",
            index=models.Index(
                fields=["report_date"], name="registers_r_report__96a3bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="register",
            index=models.Index(
                fields=["last_status"], name="registers_r_last_st_59cee7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bitacora",
            index=models.Index(
                fields=["register", "created_at"], name="registers_b_registe_022a67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bitacora",
            index=models.Index(
                fields=["user", "created_at"], name="registers_b_user_id_ac4a91_idx"
            ),
        ),
    ]
