# Generated by Django 6.0.1 on 2026-02-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='estatus_final',
            field=models.CharField(blank=True, choices=[('POSIBLE MANIPULACIÓN', 'Posible Manipulación'), ('PERDIDA DE SEÑAL', 'Perdida de Señal'), ('TALLER', 'Taller'), ('CORTACORRIENTE', 'Cortacorriente'), ('BASE', 'Base'), ('ACCIDENTADA', 'Accidentada')], help_text='Estatus final del registro (editable por usuario)', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='responsable',
            field=models.CharField(choices=[('SIN ESTATUS DEL DISTRIBUIDOR', 'Sin Estatus del Distribuidor'), ('SIN ESTATUS DEL CLIENTE', 'Sin Estatus del Cliente'), ('NO OPERACIONAL', 'No Operacional'), ('REVISIÓN FÍSICA', 'Revisión Física')], default='SIN ESTATUS DEL DISTRIBUIDOR', help_text='Responsable del seguimiento (editable por usuario)', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='tipo',
            field=models.CharField(choices=[('MAL FUNCIONAMIENTO', 'Mal Funcionamiento'), ('OPERACIÓN', 'Operación')], default='MAL FUNCIONAMIENTO', help_text='Tipo de desconexión (editable por usuario)', max_length=50),
        ),
    ]
