# Generated by Django 6.0.1 on 2026-01-29 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contrato_id",
                    models.IntegerField(help_text="ID único del contrato", unique=True),
                ),
                (
                    "vin",
                    models.CharField(
                        help_text="Número de identificación del vehículo", max_length=17
                    ),
                ),
                (
                    "contrato",
                    models.CharField(
                        help_text="Número/referencia del contrato", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contrato",
                "verbose_name_plural": "Contratos",
                "ordering": ["-contrato_id"],
                "indexes": [
                    models.Index(
                        fields=["contrato_id"], name="vehicles_co_contrat_b325b0_idx"
                    ),
                    models.Index(fields=["vin"], name="vehicles_co_vin_b1fb81_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Geofence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geo_name",
                    models.CharField(
                        help_text='Nombre de la geocerca (ej: "Base Centro")',
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Geocerca",
                "verbose_name_plural": "Geocercas",
                "ordering": ["geo_name"],
                "indexes": [
                    models.Index(
                        fields=["geo_name"], name="vehicles_ge_geo_nam_a05353_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_id",
                    models.IntegerField(
                        help_text="ID único del vehículo en sistema externo",
                        unique=True,
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        db_index=True,
                        help_text="Número de identificación del vehículo",
                        max_length=17,
                    ),
                ),
                (
                    "inner_id",
                    models.IntegerField(
                        blank=True, help_text="ID interno del vehículo", null=True
                    ),
                ),
                (
                    "last_latitude",
                    models.FloatField(
                        blank=True, help_text="Última latitud registrada", null=True
                    ),
                ),
                (
                    "last_longitude",
                    models.FloatField(
                        blank=True, help_text="Última longitud registrada", null=True
                    ),
                ),
                (
                    "last_connection",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Última conexión/ping del vehículo",
                        null=True,
                    ),
                ),
                (
                    "speed",
                    models.FloatField(
                        default=0.0,
                        help_text="Última velocidad registrada del vehículo en km/h",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contrato asociado",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicles",
                        to="vehicles.contrato",
                    ),
                ),
                (
                    "distribuidor",
                    models.ForeignKey(
                        help_text="Distribuidor responsable",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="organization.distribuidor",
                    ),
                ),
                (
                    "geofence",
                    models.ForeignKey(
                        blank=True,
                        help_text="Geocerca/Base del vehículo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicles",
                        to="vehicles.geofence",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Grupo al que pertenece el vehículo",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="organization.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehículo",
                "verbose_name_plural": "Vehículos",
                "ordering": ["-last_connection"],
                "indexes": [
                    models.Index(
                        fields=["vehicle_id"], name="vehicles_ve_vehicle_5ac43f_idx"
                    ),
                    models.Index(fields=["vin"], name="vehicles_ve_vin_d8dea1_idx"),
                    models.Index(
                        fields=["group"], name="vehicles_ve_group_i_3b02b8_idx"
                    ),
                    models.Index(
                        fields=["last_connection"],
                        name="vehicles_ve_last_co_684914_idx",
                    ),
                ],
            },
        ),
    ]
