# Generated by Django 6.0.1 on 2026-02-02 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='inner_id',
        ),
    ]
