# Generated by Django 6.0.1 on 2026-01-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrator"),
                    ("PM", "Project Manager"),
                    ("DIRECTOR", "Director cliente"),
                    ("DISTRIBUIDOR", "Distribuidor"),
                ],
                default="DISTRIBUIDOR",
                max_length=20,
            ),
        ),
    ]
